# Тема 10. Декораторы и исключения
Отчет по Теме #10 выполнил(а):
- Долгих Анатолий Сергеевич
- ИНО ЗБ ПОАС-22-1

| Задание | Сам_раб |
| ------ | ------ |
| Задание 1 | + |
| Задание 2 | + |
| Задание 3 | + |
| Задание 4 | + |
| Задание 5 | + |

знак "+" - задание выполнено; знак "-" - задание не выполнено;

Работу проверили:
- к.э.н., доцент Панов М.А.

## Самостоятельная работа №1
### Вовочка решил заняться спортивным программированием на python, но для этого он должен знать за какое время выполняется его программа.

```python
import time

def  timeCalcul(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        print('\nФункция была выполнена за %f сек.'%(end_time - start_time))
        return result
    return wrapper

@timeCalcul
def fibonacci():
    fib1 = fib2 = 1

    for i in range(2, 200):
        fib1, fib2 = fib2, fib1 + fib2
        print(fib2, end=' ')

if __name__ == '__main__':
    fibonacci()
```
### Результат.
![Меню](https://github.com/SuslickSLS/-SoftwareEngineering/blob/%D0%A2%D0%B5%D0%BC%D0%B0_10/Image/1.png)

## Выводы
Сравнение возвращает булевое значение
  
## Самостоятельная работа №2
### Посмотрев на Вовочку, вы также загорелись идеей спортивного программирования, начав тренировки вы узнали, что для решения некоторых задач необходимо считывать данные из файлов. Но через некоторое время вы столкнулись с проблемой что файлы бывают пустыми, и вы не получаете вводные данные для решения задачи. После этого вы решили не просто считывать данные из файла, а всю конструкцию оборачивать в исключения, чтобы избежать такой проблемы. Создайте пустой файл и файл, в котором есть какая-то информация. Напишите код программы. Если файл пустой, то, нужно вызвать исключение (“бросить исключение”) и вывести в консоль “файл пустой”, а если он не пустой, то вывести информацию из файла.

```python
def readFile(fileName):
    try:
        file = open(fileName,'r',encoding='utf-8')
        text = file.read()

        if not text:
            raise Exception("Пустой")

        print(text)
    except Exception as e:
        print(str(e))

readFile("Lab10_1_1.txt")
readFile("Lab10_1_2.txt")
```

### Результат.
![Меню](https://github.com/SuslickSLS/-SoftwareEngineering/blob/%D0%A2%D0%B5%D0%BC%D0%B0_10/Image/2.png)

  
## Самостоятельная работа №3
### Напишите функцию, которая будет складывать 2 и введенное пользователем число, но если пользователь введет строку или другой неподходящий тип данных, то в консоль выведется ошибка “Неподходящий тип данных. Ожидалось число.”. Реализовать функционал программы необходимо через try/except и подобрать правильный тип исключения. Создавать собственное исключение нельзя. Проведите несколько тестов, в которых исключение вызывается и нет. Результатом выполнения задачи будет листинг кода и получившийся вывод в консоль.

```python
def Sum():
    try:
        userInput = float(input('Введите число: '))
        return userInput + 2
    except ValueError:
        return 'Не тот тип.'

print(Sum())
print(Sum())
```
### Результат.
![Меню](https://github.com/SuslickSLS/-SoftwareEngineering/blob/%D0%A2%D0%B5%D0%BC%D0%B0_10/Image/3.png)

  
## Самостоятельная работа №4
### Создайте собственный декоратор, который будет использоваться для двух любых вами придуманных функций. Декораторы, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс декоратора, две как-то связанными с ним функциями, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.

```python
class MyDecorator:

    def __init__(self, func):
        self.func = func

    def __call__(self, *args, **kwargs):
        print("Выполнение функции ",self.func.__name__)

        result = self.func(*args, **kwargs)

        return result
@MyDecorator
def HelloPeople(firstName,lastName):
        return "Hello " + firstName + " " + lastName

@MyDecorator
def Addition():
    try:
        one = int(input('Введите первое значние: '))
        two = int(input('Введите второе значние: '))
        return "Сложение: " + str(one + two)
    except TypeError:
        return "Не тот тип"


firstName = input('Введите firstName: ')
lastName = input('Введите вlastName: ')

print(HelloPeople(firstName, lastName))
print(Addition())
```
### Результат.
![Меню](https://github.com/SuslickSLS/-SoftwareEngineering/blob/%D0%A2%D0%B5%D0%BC%D0%B0_10/Image/4.png)

  
## Самостоятельная работа №5
### Создайте собственное исключение, которое будет использоваться в двух любых фрагментах кода. Исключения, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс исключения, код к котором в двух местах используется это исключение, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.

```python
class GameError(Exception):
    def __init__(self, message):
        self.__message = message
        super().__init__(self.__message)


def Division(oneNumber,twoNumber):
    try:
       if(twoNumber == 0):
           raise GameError("Печаль")

       print(oneNumber/twoNumber)
    except GameError:
        print("Печаль ")

def GameLogin():
    try:
        username = input("Введите логин: ")
        password = input("Введите пароль: ")
        
        if username != "Suslick" or password != "12345":
            raise GameError("Неправильное имя или пароль:(.")
    except GameError :
        print("Неправильное имя или пароль:(")

Division(3,0)
Division(6,2)



GameLogin()
GameLogin()
```
### Результат.
![Меню](https://github.com/SuslickSLS/-SoftwareEngineering/blob/%D0%A2%D0%B5%D0%BC%D0%B0_10/Image/5.png)


## Общие выводы по теме
- Развернутый вывод
